#!/bin/sh

python scripts/compile_scss.py tornado_reader/static/css/style.scss
imba compile tornado_reader/static/js/

while true; do
	inotifywait -e modify -e move -r tornado_reader/static
	python scripts/compile_scss.py tornado_reader/static/css/style.scss
	imba compile tornado_reader/static/js/
done
